import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import { TextField } from "@mui/material";
import { useState } from "react";

export default function AdminMenu() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Admin Menu</h2>

        <div className={styles.grid}>
          <a href={url + "/statsMenu"} className={styles.card}>
            <h2>View Stats &rarr;</h2>
          </a>
          <a href={url + "/createCorporation"} className={styles.card}>
            <h2>Create Corporation &rarr;</h2>
          </a>
          <a href={url + "/createFee"} className={styles.card}>
            <h2>Create Fee &rarr;</h2>
          </a>
          <a href={url + "/manageUsers"} className={styles.card}>
            <h2>Manage Users &rarr;</h2>
          </a>
          <a href={url + "/manageOverdraft"} className={styles.card}>
            <h2>Manage Overdraft &rarr;</h2>
          </a>
          <a href={url + "/hireWorker"} className={styles.card}>
            <h2>Hire Worker &rarr;</h2>
          </a>
          <a href={url + "/payEmployees"} className={styles.card}>
            <h2>Pay Employees &rarr;</h2>
          </a>
          <a href={url + "/replaceManager"} className={styles.card}>
            <h2>Replace Manager &rarr;</h2>
          </a>
          <a href={url + "/manageAccounts"} className={styles.card}>
            <h2>Manage Accounts &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
}
