import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import { TextField } from "@mui/material";
import { useState } from "react";
import { Link } from "next/link";

export default function AdminMenu() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Admin Menu</h2>

        <div className={styles.grid}>
          <Link href={"/statsMenu"}>
            <a className={styles.card}>
              <h2>View Stats &rarr;</h2>
            </a>
          </Link>

          <Link href={"/createCorporation"}>
            <a className={styles.card}>
              <h2>Create Corporation &rarr;</h2>
            </a>
          </Link>

          <Link href={"/createFee"}>
            <a className={styles.card}>
              <h2>Create Fee &rarr;</h2>
            </a>
          </Link>

          <Link href={"/manageUsers"}>
            <a className={styles.card}>
              <h2>Manage Users &rarr;</h2>
            </a>
          </Link>

          <Link href={"/manageOverdraft"}>
            <a className={styles.card}>
              <h2>Manage Overdraft &rarr;</h2>
            </a>
          </Link>

          <Link href={"/hireWorker"}>
            <a className={styles.card}>
              <h2>Hire Worker &rarr;</h2>
            </a>
          </Link>

          <Link href={"/payEmployees"}>
            <a className={styles.card}>
              <h2>Pay Employees &rarr;</h2>
            </a>
          </Link>

          <Link href={"/replaceManager"}>
            <a className={styles.card}>
              <h2>Replace Manager &rarr;</h2>
            </a>
          </Link>

          <Link href={"/manageAccounts"}>
            <a className={styles.card}>
              <h2>Manage Accounts &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
