import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import {
  Grid,
  Paper,
  TextField,
  Button,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from "@mui/material";

export async function getServerSideProps() {
  const personIDs = await fetch(url + `/api/getPeople`);
  const personIDsJSON = await personIDs.json();

  let personInit = personIDsJSON[0]["perID"];

  // Pass data to the page via props
  return {
    props: { personIDsJSON, personInit },
  };
}

export default function createEmployee(props) {
  const [person, setPerson] = useState(props.personInit);
  const [salary, setSalary] = useState(0);
  const [numPayments, setNumPayments] = useState(0);
  const [accumEarnings, setAccumEarnings] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={1}>
        <Grid item xs={12}>
          <h1 className={styles.title}>Create Employee</h1>
        </Grid>

        <Grid item xs={2} />
        <Grid item xs={4}>
          <FormControl fullWidth>
            <InputLabel>Person</InputLabel>
            <Select
              label="Person"
              value={person}
              onChange={(e) => setPerson(e.target.value)}
            >
              {props.personIDsJSON.map((obj, i) => {
                let perID = obj["perID"];
                return (
                  <MenuItem key={i} value={perID}>
                    {perID}
                  </MenuItem>
                );
              })}
            </Select>
          </FormControl>
        </Grid>
        <Grid item xs={4}>
          <TextField
            label="Salary"
            type="number"
            fullWidth
            value={salary}
            onChange={(e) => setSalary(e.target.value)}
          />
        </Grid>
        <Grid item xs={2} />

        <Grid item xs={2} />
        <Grid item xs={4}>
          <TextField
            label="# of Payments"
            type="number"
            fullWidth
            value={numPayments}
            onChange={(e) => setNumPayments(e.target.value)}
          />
        </Grid>
        <Grid item xs={4}>
          <TextField
            label="Accumulated Earnings"
            type="number"
            fullWidth
            value={accumEarnings}
            onChange={(e) => setAccumEarnings(e.target.value)}
          />
        </Grid>

        <Grid item xs={2} />

        <Grid item xs={2} />

        <Grid item xs={4}>
          <Button variant="contained" fullWidth>
            Cancel
          </Button>
        </Grid>
        <Grid item xs={4}>
          <Button variant="contained" fullWidth>
            Create
          </Button>
        </Grid>
        <Grid item xs={2} />
      </Grid>
    </div>
  );
}
