import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import { TextField } from "@mui/material";
import { useState } from "react";

export default function CustomerMenu() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <h2 className={styles.title}>Customer Menu</h2>

        <div className={styles.grid}>
          <a href={url + "/manageAccounts"} className={styles.card}>
            <h2>Manage Accounts &rarr;</h2>
          </a>
          <a href={url + "/depositOrWithdrawal"} className={styles.card}>
            <h2>Deposit / Withdrawal &rarr;</h2>
          </a>
          <a href={url + "/manageOverdraft"} className={styles.card}>
            <h2>Manage Overdraft &rarr;</h2>
          </a>
          <a href={url + "/makeTransfer"} className={styles.card}>
            <h2>Make Transfer &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
}