import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import { Button, TextField } from "@mui/material";
import { useState } from "react";

export default function Login() {
  const [userID, setUserID] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState("");

  const Login = async (userID, password) => {
    const rawResponse = await fetch(url + "/api/login", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ userID: userID, password: password }),
    });
    const response = await rawResponse.json();
    console.log(response);
    if (response && response.length > 0) {
      setRole(response[0].role);
      setUserID(response[0].perID);
    } else {
      alert("Login Unsuccessful");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {role === "" && (
          <>
            <h2 className={styles.title}>Login</h2>
            <h2>User ID: </h2>
            <TextField
              value={userID}
              onChange={(e) => setUserID(e.target.value)}
              style={{ width: 500 }}
            ></TextField>
            <h2>Password: </h2>
            <TextField
              type={"password"}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={{ width: 500 }}
            ></TextField>
            <Button
              variant="contained"
              style={{ width: 500, marginTop: 50, padding: 20 }}
              onClick={() => Login(userID, password)}
            >
              Login
            </Button>
            <h4>Don't have an account? </h4>
            <a style={{ color: "blue" }} href={url + "/register"}>
              {" "}
              Register Here!
            </a>
          </>
        )}

        {role !== "" && <h2 className={styles.title}>Welcome {userID}!</h2>}

        {role === "a" && (
          <>
            <a href={url + "/adminMenu"} className={styles.card}>
              <h2>Login as Admin &rarr;</h2>
            </a>
          </>
        )}

        {(role === "e" || role === "e&c") && (
          <>
            <a href={url + "/managerMenu"} className={styles.card}>
              <h2>Login as Manager &rarr;</h2>
            </a>
          </>
        )}

        {(role === "c" || role === "e&c") && (
          <>
            <a href={url + "/customerMenu"} className={styles.card}>
              <h2>Login as Customer &rarr;</h2>
            </a>
          </>
        )}
      </main>
    </div>
  );
}
