import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import { TextField } from "@mui/material";
import { useState } from "react";

export default function ManagerMenu() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Manager Menu</h2>

        <div className={styles.grid}>
          <a href={url + "/payEmployee"} className={styles.card}>
            <h2>Pay Employee &rarr;</h2>
          </a>
          <a href={url + "/hireWorker"} className={styles.card}>
            <h2>Hire Worker &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
}
