import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import {
  Grid,
  Paper,
  TextField,
  Button,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from "@mui/material";

export async function getServerSideProps() {
  const employeeIDs = await fetch(url + `/api/getEmployeeIDs`);
  const employeeIDsJSON = await employeeIDs.json();

  const customerIDs = await fetch(url + `/api/getCustomerIDs`);
  const customerIDsJSON = await customerIDs.json();

  let employeeInit = employeeIDsJSON[0]["perID"];
  let customerInit = customerIDsJSON[0]["perID"];

  // Pass data to the page via props
  return {
    props: { employeeIDsJSON, employeeInit, customerIDsJSON, customerInit },
  };
}

export default function manageUsers(props) {
  const [employee, setEmployee] = useState(props.employeeInit);
  const [customer, setCustomer] = useState(props.customerInit);

  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={1}>
        <Grid item xs={12}>
          <h1 className={styles.title}>Stop Customer Role</h1>
        </Grid>

        <Grid item xs={2} />
        <Grid item xs={8}>
          <FormControl fullWidth>
            <InputLabel>Customer</InputLabel>
            <Select
              label="Customer"
              value={customer}
              onChange={(e) => setCustomer(e.target.value)}
            >
              {props.customerIDsJSON.map((obj, i) => {
                let perID = obj["perID"];
                return (
                  <MenuItem key={i} value={perID}>
                    {perID}
                  </MenuItem>
                );
              })}
            </Select>
          </FormControl>{" "}
        </Grid>

        <Grid item xs={2} />

        <Grid item xs={2} />

        <Grid item xs={4}>
          <Button variant="contained" fullWidth>
            {" "}
            Cancel{" "}
          </Button>
        </Grid>
        <Grid item xs={4}>
          <Button variant="contained" fullWidth>
            {" "}
            Confirm{" "}
          </Button>
        </Grid>
        <Grid item xs={2} />

        <Grid item xs={12}>
          <h1 className={styles.title}>Stop Employee Role</h1>
        </Grid>

        <Grid item xs={2} />
        <Grid item xs={8}>
          <FormControl fullWidth>
            <InputLabel>Employee</InputLabel>
            <Select
              label="Employee"
              value={employee}
              onChange={(e) => setEmployee(e.target.value)}
            >
              {props.employeeIDsJSON.map((obj, i) => {
                let perID = obj["perID"];
                return (
                  <MenuItem key={i} value={perID}>
                    {perID}
                  </MenuItem>
                );
              })}
            </Select>
          </FormControl>{" "}
        </Grid>

        <Grid item xs={2} />

        <Grid item xs={2} />

        <Grid item xs={4}>
          <Button variant="contained" fullWidth>
            {" "}
            Cancel{" "}
          </Button>
        </Grid>
        <Grid item xs={4}>
          <Button variant="contained" fullWidth>
            {" "}
            Confirm{" "}
          </Button>
        </Grid>
        <Grid item xs={2} />
      </Grid>
    </div>
  );
}
