import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { url } from "../lib/env";
import { TextField } from "@mui/material";
import { useState } from "react";

export default function StatsMenu() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank Management UI Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>View Stats</h2>

        <div className={styles.grid}>
          <a href={url + "/accountView"} className={styles.card}>
            <h2>Account Stats &rarr;</h2>
          </a>

          <a href={url + "/bankView"} className={styles.card}>
            <h2>Bank Stats &rarr;</h2>
          </a>

          <a href={url + "/corporationView"} className={styles.card}>
            <h2>Corporation Stats &rarr;</h2>
          </a>

          <a href={url + "/customerView"} className={styles.card}>
            <h2>Customer Stats &rarr;</h2>
          </a>

          <a href={url + "/employeeView"} className={styles.card}>
            <h2>Employee Stats &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
}
